name: Actions Windows 😎
on:
  workflow_dispatch: {}
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: StandaloneWindows64
      - uses: actions/upload-artifact@v2
        with:
          name: build-Windows
          path: build
      
  send_to_ftp:
    name: Send to FTP
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build-Windows
          path: build
      - name: Send to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: build
          remoteDir: ${{ secrets.FTP_PATH }}
